//Dependencies
var express = require('express'); // The main framework
var path = require('path'); // Used to merge paths efficiently 
var bodyParser = require('body-parser'); //used to parse body of the request
var logger = require('morgan'); // used to log request url type and response code in the terminal
var cookieParser = require('cookie-parser')

var app = express();

var fileUpload = require('express-fileupload');
//require controller
var initDb = require('./config/mongoInit.js').initDb ;
initDb() ;

superSecret = require('./config/config').key ;

//require routes
var loginHandler = require('./routes/loginHandler.js')
var signUpHandler = require('./routes/signUpHandler.js')
var addNewHandler = require('./routes/addNewHandler')
var viewSnippet  = require('./routes/view_snippet')
var profile = require('./routes/profile')
var postExpiryHandler = require('./routes/postExpiryHandler')

//require middlewares

var authenticate = require('./middlewares/authenticate')


app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
app.use(fileUpload());

app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser())

// Static files provider for public directory
app.use(express.static(path.join(__dirname, 'public')))


//Routes
app.use('/login',loginHandler)
app.use('/signup',signUpHandler)
app.use(postExpiryHandler)
app.use('/view_snippet', viewSnippet)
app.use(authenticate)
app.use('/view_snippet/:id',function(req, res, next){
	Code.findOne({url : req.params.id}, function(err, snippet){
		if(snippet){
			if(snippet.owner === req.decoded._doc.username)
				res.render('view_snippet', {snippet:snippet,message:''})
			else{
				res.render('error',{message:'Sorry, you aren\'t permitted'})	
			}
		}else{
			res.render('error',{message:'The snippet doesn\'t exist'})
		}
	})
})
app.use('/add_new', addNewHandler)
app.use('/profile', profile)
app.get('/',function(req, res, next){
	res.redirect('profile')
})
// this error handler was generated by express-generator and for development environment only
app.use(function(err, req, res, next) {
	console.log(err)
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.end('error');
});

app.use(function(req,res){
  res.render('error', {message: ''})
})
app.listen(3000)